---
- name: Configure EC2 instance and install Docker
  hosts: web_servers
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy application files to the server
      copy:
        src: ./sample_app/  # The directory containing Dockerfile, app.py, etc.
        dest: /home/ec2-user/sample_app/
        owner: ec2-user
        group: ec2-user
        mode: 0755
    
    - name: Run the Docker container
      docker_container:
        name: sample_app_container
        image: sample_app
        state: started
        published_ports:
          - "80:80"